### ISSUE TITLE
Raspberry PI 4 is not starting when using the image

### ISSUE THREAD

**Issue by StPaulis** [balena-labs-projects/balena-node-red#46]
I have tried to use this image in several raspberry 4 devices and it seems that is not booting as expected so I can not see my device in my relative fleet. 

### How to reproduce

- Go [in that page](https://github.com/balena-labs-projects/balena-node-red) and create a new fleet by clicking in the button
- Add a device in the newly created fleet (choose raspberry pi 4 as the device of preference)
- Use etcher to boot the SD card with the image that I have downloaded
- Put the image in the raspberry pi 4

### Expected behavior

To see the device in my fleet after some seconds and be able to use Node Red when I enable the public URL.

### Actual behavior

Once it is powered on, both green and red light of the raspberry pi stays on. I don't see the device in my fleets or I see anything when I enter the HDMI. I have tried the same process to different devices.

### Notes

Looking at the code I think that [the base image](https://github.com/balena-labs-projects/balena-node-red/blob/master/node-red/Dockerfile.raspberrypi4-64#L4) should be referencing the version 4 but I have not tried to change that yet, neither I am sure that this is the cause of the problem.

**Comment by phil-d-wilson** [comment]
Hey there,

Sorry it's taken so long for us to get back to you. I'd point out how busy everyone is, but that's not a decent excuse. We are actively thinking through how to better support our blocks, or archive them if we can't support all the things we've ever made.

In this case, the issue wasn't about using a Pi3 image on a Pi4. A Pi4 can run base 32-bit images just fine.
The issue was that it was running a really old version of debian, and the packages were not being found any more. I've updated the base images and the packages to reference Python3, and tested it all on a Pi4 and a Pi3 for completeness.

All seems fine now.
